# Generated by Django 4.1.4 on 2023-01-07 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_published', models.DateField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('words', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=220, null=True)),
                ('message', models.TextField(blank=True, max_length=9000, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', max_length=2500, null=True)),
                ('commented_by', models.CharField(blank=True, max_length=120, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('replies', models.IntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('message', models.CharField(default='', max_length=1200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('img', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('cover', models.URLField(default='', max_length=1000)),
                ('cover_source', models.URLField(default='', max_length=50)),
                ('excerpt', models.TextField(default='', max_length=2000)),
                ('description', models.TextField(default='', max_length=5000)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('words', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Spoken-Word', 'Spoken-Word'), ('Poetic-Chains', 'Poetic-Chains'), ('Poetic-Notes', 'Poetic-Notes'), ('One-Liners', 'One-Liners'), ('Poems', 'Poems')], default='', max_length=60)),
                ('tag', models.CharField(blank=True, choices=[('love', 'love'), ('life', 'life')], default='', max_length=60, null=True)),
                ('status', models.CharField(blank=True, choices=[('pinned', 'pinned'), ('unpinned', 'unpinned')], default='', max_length=60, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=220, null=True, unique=True)),
                ('date_subscribed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=120)),
                ('cover', models.URLField(default='', max_length=1000)),
                ('author_pic', models.URLField(default='', max_length=1000)),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='', max_length=5000)),
                ('category', models.CharField(choices=[('short-story', 'short-story'), ('novel', 'novel'), ('novelette', 'novelette'), ('play', 'play'), ('flash-fiction', 'flash-fiction')], default='', max_length=60)),
                ('genre', models.CharField(choices=[('mystery', 'mystery'), ('thriller', 'thriller'), ('drama', 'drama'), ('mystery/thriller', 'mystery/thriller'), ('action', 'action'), ('romance', 'romance'), ('teen-fiction', 'teen-fiction')], default='', max_length=60)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_published', models.DateField(default=django.utils.timezone.now)),
                ('pin', models.CharField(blank=True, choices=[('pinned', 'pinned'), ('unpinned', 'unpinned')], default='', max_length=60, null=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing')], default='', max_length=60)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('words', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('chaps', models.IntegerField(blank=True, null=True)),
                ('tagged', models.ManyToManyField(blank=True, null=True, to='benie_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, max_length=2500, null=True)),
                ('replied_by', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], default='', max_length=60, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.chapter')),
                ('comment', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.feedback')),
                ('poem', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.poem')),
                ('story', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('cover', models.URLField(default='', max_length=1000)),
                ('description', models.TextField(default='', max_length=5000)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('words', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.chapter')),
                ('story', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='poem',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.poem'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story'),
        ),
    ]
