# Generated by Django 4.1.4 on 2022-12-13 14:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Story Cover')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('mystery', 'mystery'), ('thriller', 'thriller'), ('drama', 'drama'), ('mystery/thriller', 'mystery/thriller'), ('action', 'action'), ('romance', 'romance')], max_length=60)),
                ('tagged', models.ManyToManyField(to='benie_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Chapter Cover')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('Story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benie_app.story')),
            ],
        ),
    ]
