# Generated by Django 4.1.4 on 2022-12-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Story',
            new_name='story',
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, default=False, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benie_app.story')),
            ],
        ),
    ]
