# Generated by Django 4.1.4 on 2023-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, default='Beautiful piece!', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='commented_by',
            field=models.CharField(blank=True, default='Anonymous', max_length=120, null=True),
        ),
    ]
