# Generated by Django 4.1.4 on 2022-12-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=2500, null=True)),
                ('chapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='benie_app.chapter')),
            ],
        ),
    ]
