# Generated by Django 4.1.4 on 2023-01-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='cover_source',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
