# Generated by Django 4.1.4 on 2023-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0002_alter_feedback_comment_alter_feedback_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='msg',
            field=models.TextField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replied_by',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
