# Generated by Django 4.1.4 on 2022-12-15 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='first_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chapter',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='first_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='story',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('com', 'completed'), ('on', 'ongoing')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('mys', 'mystery'), ('thr', 'thriller'), ('dr', 'drama'), ('mys/thr', 'mystery/thriller'), ('act', 'action'), ('rom', 'romance')], default='', max_length=60),
        ),
    ]
