# Generated by Django 4.1.4 on 2023-01-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0003_alter_reply_msg_alter_reply_replied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('mystery', 'mystery'), ('drama', 'drama'), ('thriller', 'thriller'), ('drama', 'drama'), ('mystery/thriller', 'mystery/thriller'), ('action', 'action'), ('romance', 'romance'), ('teen-fiction', 'teen-fiction')], default='', max_length=60),
        ),
    ]
