# Generated by Django 4.1.4 on 2023-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0004_alter_story_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='chap1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
