# Generated by Django 4.1.4 on 2022-12-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0004_rename_first_created_chapter_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tagged',
            field=models.ManyToManyField(blank=True, null=True, to='benie_app.tag'),
        ),
    ]
