# Generated by Django 4.1.4 on 2023-01-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0005_story_chap1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('mystery', 'mystery'), ('drama', 'drama'), ('thriller', 'thriller'), ('drama', 'drama'), ('mystery-thriller', 'mystery-thriller'), ('action', 'action'), ('romance', 'romance'), ('teen-fiction', 'teen-fiction')], default='', max_length=60),
        ),
    ]
