# Generated by Django 4.1.4 on 2023-01-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0006_reply_story_alter_story_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='poem',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.poem'),
        ),
    ]
