# Generated by Django 4.1.4 on 2022-12-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0006_remove_chapter_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story'),
        ),
    ]
