# Generated by Django 4.1.4 on 2022-12-16 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0007_alter_chapter_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
