# Generated by Django 4.1.4 on 2022-12-16 09:35

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0008_feedback_date_reaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='benie_app.story'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='chapter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benie_app.chapter'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='chapter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='benie_app.chapter'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='Story Cover'),
        ),
    ]
