# Generated by Django 4.1.4 on 2022-12-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0009_alter_chapter_story_alter_feedback_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
