# Generated by Django 4.1.4 on 2022-12-18 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0012_remove_chapter_description_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
