# Generated by Django 4.1.4 on 2022-12-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0016_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.story'),
        ),
    ]
