# Generated by Django 4.1.4 on 2022-12-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0017_page_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author_pic',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
