# Generated by Django 4.1.4 on 2022-12-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0018_story_author_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=120)),
                ('author_pic', models.URLField(default='', max_length=1000)),
                ('subject', models.CharField(default='', max_length=120)),
                ('message', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
