# Generated by Django 4.1.4 on 2022-12-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0020_feedback_story_alter_feedback_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='story',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='benie_app.story'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='chapter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='benie_app.chapter'),
        ),
    ]
