# Generated by Django 4.1.4 on 2022-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0021_reaction_story_alter_reaction_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='like',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], default='', max_length=60, null=True),
        ),
    ]
