# Generated by Django 4.1.4 on 2022-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0022_alter_reaction_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='commented_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
