# Generated by Django 4.1.4 on 2022-12-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0024_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=220, null=True, unique=True),
        ),
    ]
