# Generated by Django 4.1.4 on 2022-12-19 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0025_alter_subscriber_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='author_pic',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='subject',
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
