# Generated by Django 4.1.4 on 2022-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0027_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
