# Generated by Django 4.1.4 on 2022-12-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0028_page_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
