# Generated by Django 4.1.4 on 2022-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0031_alter_feedback_chapter_alter_feedback_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=60, null=True),
        ),
    ]
