# Generated by Django 4.1.4 on 2022-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0032_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
