# Generated by Django 4.1.4 on 2022-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0034_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=9000, null=True),
        ),
    ]
