# Generated by Django 4.1.4 on 2022-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0035_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=220, null=True),
        ),
    ]
