# Generated by Django 4.1.4 on 2023-01-02 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0036_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='', max_length=5000)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('words', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='cover',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='feedback',
            name='poem',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.poem'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='poem',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='benie_app.poem'),
        ),
    ]
