# Generated by Django 4.1.4 on 2023-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0037_poem_page_cover_feedback_poem_reaction_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('Spoken Word', 'Spoken Word'), ('Poetic Chains', 'Poetic Chains'), ('Poetic Notes', 'Poetic Notes'), ('One-Liners', 'One-Liners')], default='', max_length=60),
        ),
    ]
