# Generated by Django 4.1.4 on 2023-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0038_poem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='status',
            field=models.CharField(blank=True, choices=[('pinned', 'pinned'), ('unpinned', 'unpinned')], default='', max_length=60, null=True),
        ),
    ]
