# Generated by Django 4.1.4 on 2023-01-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0040_poem_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='tag',
            field=models.CharField(choices=[('love', 'love'), ('life', 'life')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('Spoken Word', 'Spoken Word'), ('Poetic Chains', 'Poetic Chains'), ('Poetic Notes', 'Poetic Notes'), ('One-Liners', 'One-Liners'), ('Poem', 'Poem')], default='', max_length=60),
        ),
    ]
