# Generated by Django 4.1.4 on 2023-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0041_poem_tag_alter_poem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='tag',
            field=models.CharField(blank=True, choices=[('love', 'love'), ('life', 'life')], default='', max_length=60, null=True),
        ),
    ]
