# Generated by Django 4.1.4 on 2023-01-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0042_alter_poem_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='excerpt',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
