# Generated by Django 4.1.4 on 2023-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0043_poem_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='cover_att',
            field=models.CharField(default='', max_length=50),
        ),
    ]
