# Generated by Django 4.1.4 on 2023-01-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0044_poem_cover_att'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='cover_att',
        ),
        migrations.AddField(
            model_name='poem',
            name='cover_source',
            field=models.URLField(default='', max_length=50),
        ),
    ]
