# Generated by Django 4.1.4 on 2023-01-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0045_remove_poem_cover_att_poem_cover_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
