# Generated by Django 4.1.4 on 2023-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0046_alter_poem_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('Spoken-Word', 'Spoken-Word'), ('Poetic-Chains', 'Poetic-Chains'), ('Poetic-Notes', 'Poetic-Notes'), ('One-Liners', 'One-Liners'), ('Poems', 'Poems')], default='', max_length=60),
        ),
    ]
