# Generated by Django 4.1.4 on 2023-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0048_reaction_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
