# Generated by Django 4.1.4 on 2023-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0049_poem_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
