# Generated by Django 4.1.4 on 2023-01-05 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0050_feedback_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_replied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replied_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
