# Generated by Django 4.1.4 on 2023-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0051_feedback_date_replied_feedback_replied_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='replies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply_msg',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
