# Generated by Django 4.1.4 on 2023-01-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0052_feedback_replies_feedback_reply_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_replied',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='replied_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reply_msg',
        ),
    ]
